# Generated by Django 4.1.7 on 2023-05-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='tel',
            new_name='telephone',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='avatar',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
